# Generated by Django 5.2.17 on 2026-10-04 22:37

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMatafuego',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nro_serie', models.CharField(db_index=True, max_length=60, verbose_name='Nº de serie')),
                ('clase', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('ABC', 'ABC'), ('BC', 'BC'), ('D', 'D'), ('K', 'K'), ('CO2', 'CO₂'), ('AGUA', 'Agua')], max_length=5)),
                ('ubicacion', models.CharField(max_length=200, verbose_name='ubicación')),
                ('fecha_instalacion', models.DateField(verbose_name='fecha de instalación')),
                ('fecha_vencimiento_estimado', models.DateField(verbose_name='vencimiento estimado')),
                ('venc_ph', models.DateField(blank=True, null=True, verbose_name='vencimiento PH')),
                ('token_qr', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('estado_manual', models.CharField(blank=True, choices=[('VIGENTE', 'Vigente'), ('PROXIMO', 'Próximo a vencer'), ('VENCIDO', 'Vencido')], default='', max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fire.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical matafuego',
                'verbose_name_plural': 'historical matafuegos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Matafuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_serie', models.CharField(max_length=60, unique=True, verbose_name='Nº de serie')),
                ('clase', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('ABC', 'ABC'), ('BC', 'BC'), ('D', 'D'), ('K', 'K'), ('CO2', 'CO₂'), ('AGUA', 'Agua')], max_length=5)),
                ('ubicacion', models.CharField(max_length=200, verbose_name='ubicación')),
                ('fecha_instalacion', models.DateField(verbose_name='fecha de instalación')),
                ('fecha_vencimiento_estimado', models.DateField(verbose_name='vencimiento estimado')),
                ('venc_ph', models.DateField(blank=True, null=True, verbose_name='vencimiento PH')),
                ('token_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado_manual', models.CharField(blank=True, choices=[('VIGENTE', 'Vigente'), ('PROXIMO', 'Próximo a vencer'), ('VENCIDO', 'Vencido')], default='', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matafuegos', to='fire.cliente')),
            ],
            options={
                'verbose_name_plural': 'matafuegos',
                'ordering': ['fecha_vencimiento_estimado', 'nro_serie'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultado', models.CharField(choices=[('APTO', 'Apto'), ('OBSERVADO', 'Con observaciones'), ('NO_APTO', 'No apto')], max_length=10)),
                ('manometro_ok', models.BooleanField(default=True, verbose_name='manómetro en zona verde')),
                ('precinto_ok', models.BooleanField(default=True, verbose_name='precinto y traba intactos')),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matafuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='fire.matafuego')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
